### ISSUE TITLE
qt4 win64 packages are available but not in main channel

### ISSUE THREAD

**Issue by megies** [conda-forge/qt-feedstock#139]
Issue:

It seems that qt 4 packages for windows are fine, but they can not be installed with default install commands because they are not in `main` channel but rather in `cf201901` channel. This is such a simple thing but it can take a really long time to find out why installation is not working.

```
# this works
conda install pyqt=4.11.4 qt=4.8.7 -c conda-forge/label/cf201901
# but this doesnt
conda install pyqt=4.11.4 qt=4.8.7 -c conda-forge
```

Thanks @ThomasLecocq for debugging

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
`cf201901` is an epoch before the compiler migration. It may work on some situations but users should know what they want to do in order to use it otherwise they can create broken environments.

If you need a rebuild of `qt4` with modern compilers on Windows we welcome PRs to the `qt4` branch! If the old compiler version if fine for you then you'll have to use the `cf201901` label.

**Comment by megies** [comment]
I am guessing this has a high probability of not being a simple task.. i'd probably not get it done, so not dabbling with a PR. Thanks for explanations, though.

**Comment by ocefpaf** [comment]
Indeed. Not an easy task, that is why no one has done it so far ;-p
