### ISSUE TITLE
Building on Windows with MinGW

### ISSUE THREAD

**Issue by oleg-alexandrov** [conda-forge/qt-feedstock#233]
### Comment:

I am trying to do a build job on Microsoft Windows. 

I fetched qt=5.9.7 from conda-forge and tried to compile a program with m2w64-gcc=5.3.0. I get a lot of failures at link-time. I did check that the right libraries were passed to the linker and there's no invocation mistake.

Is it because this compiler and this version of Qt are incompatible? Is there a specific compiler needed to use with Qt on Windows?

Thanks.

**Comment by gillins** [comment]
conda-forge packages are built with MSVC for compatibility with Python (see https://wiki.python.org/moin/WindowsCompilers). In order to link against our packages you will need to do the same....
There is some interoperability between gcc and MSVC for C code but for C++ they are incompatible (different name mangling for a start - hence the errors you are seeing).

**Comment by oleg-alexandrov** [comment]
Thank you. This is very helpful. Not sure how one would document this better for folks running into this issue, but my question is answered.  I will close this.
