### ISSUE TITLE
PaddingError on windows install

### ISSUE THREAD

**Issue by jcrist** [conda-forge/qt-feedstock#43]
When switching to use conda-forge instead of defaults in our appveyor builds, this error came up:

```
PaddingError: Placeholder of length '29' too short in package conda-forge::qt-5.6.2-vc14_1.
The package must be rebuilt with conda-build > 2.0.
```

(see https://ci.appveyor.com/project/daskdev/dask/build/1.0.1267#L254)

Not sure if this just means the package needs to be rebuilt, or if there's a deeper issue.

**Comment by ccordoba12** [comment]
@gillins, it seems you didn't use `conda-build > 2.0` to compile Qt5 on Windows. Could you confirm that?

**Comment by gillins** [comment]
According to `about.json` in the tarfile I used `conda-build` 2.1.4.
I did have to specify `--croot=c:\qt` otherwise the build failed (paths too long). Not sure if this is related. Did you have to do the same for defaults?

**Comment by gillins** [comment]
The contents of `info/has_prefix` is below. Seems that setting `--croot` has given us a very short install prefix (29 chars). Does anyone have any thoughts about how to get the build running in a different to the install?

The build needs a short prefix otherwise the paths are too long for VC, but the install location needs to be the usual size to avoid the error reported here.

```
"c:/qt/qt_1489878162099/_b_env" binary "Library/bin/Qt5Core.dll"
"c:/qt/qt_1489878162099/_b_env" binary "Library/bin/qmake.exe"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5AxBase.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5AxContainer.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5AxServer.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5Bootstrap.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5LabsControls.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5OpenGLExtensions.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5PlatformSupport.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5QmlDevTools.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/Qt5UiTools.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/qtfreetype.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/lib/qtmain.prl"
"c:/qt/qt_1489878162099/_b_env" text "Library/mkspecs/qmodule.pri"
```

**Comment by ccordoba12** [comment]
@mingwandroid, how did you solve this issue in Continuum packages?

**Comment by jakirkham** [comment]
FWIW we ended up setting `CONDA_BLD_PATH`, which is the same as `--croot` FWICT, to `C:\\bld\\` because `boost` had issues with a longer path. This has been set for all Windows packages since January. To my knowledge this has not had any adverse effect on Windows packages that are built with `boost` or installing `boost` on Windows let alone other packages. This would only be a couple more characters than @gillins already used, but maybe doing that would be enough. Though maybe others can provide additional suggestions.

cc @isuruf @msarahan

**Comment by msarahan** [comment]
Windows should not be trying to replace prefixes in binary files.  This is a bug that is fixed in recent versions of conda.  Current 4.2 and 4.3 releases should be fine.  I don't know about 4.1 series and earlier.

**Comment by msarahan** [comment]
To clarify, conda-build began recording binary prefix data to windows binaries in order to support Pip-created entry point exe's.  Conda should (and recent versions do) understand what is and what is not one of these executables, and conda skips over things that it should not touch.

**Comment by gillins** [comment]
The log (https://ci.appveyor.com/project/daskdev/dask/build/1.0.1267#L32) seems to suggest he is using conda 4.2.9...

**Comment by msarahan** [comment]
@jcrist please update conda.  4.2.16 is the current 4.2.x release.  If you still have problems, please let me and/or @kalefranz know.
