### ISSUE TITLE
qt for windows vs15

### ISSUE THREAD

**Issue by looooo** [conda-forge/qt-feedstock#6]
[question]
to use pyside with python3.5 we need qt to be compiled with visualstudio15. Is this possible or are there any show-stoppers? I am wondering because there are no visualstudio15 qt packages available.

But there is a python3.5 pyqt4 package on the default channel. Any ideas which qt version it depends on?

**Comment by ccordoba12** [comment]
> to use pyside with python3.5 we need qt to be compiled with visualstudio15. Is this possible or are there any show-stoppers? I am wondering because there are no visualstudio15 qt packages available.

There is one version of Qt (from the default channels) which is compiled against Visual Studio 2015. So there are no show-stoppers there.

PySide packages are about to enter conda-forge, for all operating systems and Python versions:

https://github.com/conda-forge/staged-recipes/pull/1684

> Any ideas which qt version it depends on?

On Qt 4.8.7

**Comment by ccordoba12** [comment]
To be more explicit (sorry for being a bit blunt :-) there is no need (for now) to create Windows Qt packages for conda-forge because there are no conflicts between conda-forge and the packages from the default channels. However, there were important conflicts for Linux, and that's why this feedstock was created.

But even if there would be a need for those packages, right now we couldn't provide them because they can't be compiled in Appveyor. That's a insurmountable show-stopper!

There are already some discussions on how to improve this situation for big packages (like Qt or VTK) but nothing has been decided yet.

**Comment by looooo** [comment]
thanks, for the information. this are great news for freecad. if there will exist a conda-forge pyside for win and python3.5 I think it should be possible to provide packages of freecad on all platforms via conda... 
thanks for your good work and support.
